import os

Import('env')

penv = env.Clone()

src = [
    "client.c",
    "rand.c",
    "triple.c",
]

libs = [
]

# Enable mp_print()
penv.Append(CFLAGS = ['-DMP_IOFUNC'])

penv.Append(LIBS = libs)
penv.StaticLibrary("libprio", src)

