import os

Import('env')

penv = env.Clone()

src = [
    "client.c",
    "config.c",
    "fft.c",
    "mparray.c",
    "rand.c",
    "server.c",
    "share.c",
]

libs = [
]

# Enable mp_print()
penv.Append(CFLAGS = ['-DMP_IOFUNC'])

penv.Append(LIBS = libs)
penv.StaticLibrary("libmprio", src)

