import sys

Import('env')

balloon_env = env.Clone()

test_srcs = [
    "mutest.c",
    "example_test.c",
]

libs = [
  "libprio",
]

# Run the mutest script to generate the test harness code
bld = Builder(action = 'ptest/mkmutest ptest/mutest.h $SOURCES | $CC -c -xc -o $TARGET -')
balloon_env.Append(BUILDERS = {'MkMutest' : bld})

balloon_env.Append(LIBS = libs)

# Copy the mutest scripts to the build dir
balloon_env.Install("mkmutest")
balloon_env.Install("mutest.h")

test_objs = balloon_env.Object(test_srcs)
test_main = balloon_env.MkMutest(test_objs)
balloon_env.Program("ptest", [test_main] + test_objs)

